### PR TITLE
Autoreload support

### PR DESCRIPTION
**Pull request by whisperity**
I put together a quick fix to prevent the print hooks registering every time the Luas are reloaded. So no more ten times printing out the same transmitted variable. :smile:

### CODE REVIEW

**Comment by ottworks** [comment]
I don't know, I designed this to be discreet and use no global variables.

**Comment by whisperity** [comment]
It can't be discreet because at the moment someone calls `debug.getinfo(net.Start)`, they will see where the function is implemented.
Unfortunately, there's no way to support auto-reload without a variable... or maybe there is.
Wait, I think I've got an idea. :thought_balloon:

**Comment by bmwalters** [comment]
that's special
edit: the whole "discreet" thing is dumb, anyone can just detour CreateConVar and check for "nethack"!

**Comment by ottworks** [comment]
idk it just seems dirty to me

**Comment by zerfgog** [comment]
ur mom

**Pull request merged**
